server:
    port: 8056
 
spring:
 
    datasource:
        url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf-8
        username: root
        password: 123
        driver-class-name: com.mysql.cj.jdbc.Driver
        
mybatis:
    type-aliases-package: com.xyhy.blog.mybatis.mapper
    mapper-locations: classpath:mybatis/mapper/*.xml  
    
jwt:   
    expire_millis: "60000"
    secrit_code: "thisissecritecode"

filePath : "G:/image/"